### ISSUE TITLE
Overleaf errors

### ISSUE THREAD

**Issue by longtruong2604** [meterglost/HCMUT-Latex-report-template#1]
Hi, I'm having some issues while compiling via Overleaf. I followed your instructions and uploaded the zip version of scr as well as changed the compiler to XeLateX. However, it kept saying that fonts could not be found, I checked everything and there seemed to be no problem though. The fonts were there and the path looked good. 

```
"Package fontspec Error: The font "IBMPlexSerif-Regular" cannot be found."
Font \TU/IBMPlexSerif(0)/m/n/10=[IBMPlexSerif-Regular.ttf]:mode=harf;language=dflt;+tlig; at 10pt not loadable: metric data not found or bad.
```
There are 128 issues in total and they look similar to that of the above. 

Did you have the same problem and if so, could you guide me on how to resolve it. Thanks in advance.

**Comment by meterglost** [comment]
This is step-by-step guild for Overleaf:

1. Download `src.zip`
2. Select _New Project > Upload Project > Select src.zip file_
3. Select _Menu > Compiler > XeLaTeX_
4. Select _Recompile_

I have tested and there are only some overfull hbox, no error or warning.
